# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
import os

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(430, 145)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slider = QtWidgets.QSlider(self.centralwidget)
        self.slider.setEnabled(False)
        self.slider.setGeometry(QtCore.QRect(120, 110, 161, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
#         self.slider.setPalette(palette)
#         self.slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
#         self.slider.setStyleSheet("\n"
# "QSlider::groove:horizontal {  \n"
# "                height: 10px;\n"
# "                margin: 0px;\n"
# "                border-radius: 5px;\n"
# "                background: #B0AEB1;\n"
# "            }\n"
# "QSlider::handle:horizontal {\n"
# "                background: #D9D4D8;\n"
# "                border: 1px solid #C7C3C6;\n"
# "                width: 17px;\n"
# "                margin: -5px 0; \n"
# "                border-radius: 8px;\n"
# "            }\n"
# "QSlider::sub-page:qlineargradient {\n"
# "                background: #3B99FC;\n"
# "                border-radius: 5px;\n"
# "            }")
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 300, 51))
        self.textEdit.setObjectName("textEdit")
        self.radioEncode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioEncode.setGeometry(QtCore.QRect(20, 80, 95, 20))
        self.radioEncode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioEncode.setObjectName("radioEncode")
        self.radioDecode = QtWidgets.QRadioButton(self.centralwidget)
        self.radioDecode.setGeometry(QtCore.QRect(150, 80, 95, 20))
        self.radioDecode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioDecode.setObjectName("radioDecode")
        self.radioNoise = QtWidgets.QRadioButton(self.centralwidget)
        self.radioNoise.setGeometry(QtCore.QRect(20, 110, 71, 20))
        self.radioNoise.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioNoise.setObjectName("radioNoise")
        self.buttonBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.buttonBrowse.setEnabled(False)
        self.buttonBrowse.setGeometry(QtCore.QRect(330, 20, 91, 31))
        self.buttonBrowse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBrowse.setObjectName("buttonBrowse")
        self.buttonEnter = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEnter.setEnabled(True)
        self.buttonEnter.setGeometry(QtCore.QRect(330, 90, 91, 31))
        self.buttonEnter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonEnter.setStyleSheet("")
        self.buttonEnter.setObjectName("buttonEnter")
        self.errors = QtWidgets.QTextEdit(self.centralwidget)
        self.errors.setReadOnly(True)
        self.errors.setGeometry(QtCore.QRect(290, 110, 21, 21))
        self.errors.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.errors.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.errors.setObjectName("errors")
        self.errors.setText('1')
        self.errors.setEnabled(False)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная №4"))
        self.radioEncode.setText(_translate("MainWindow", "Закодировать"))
        self.radioDecode.setText(_translate("MainWindow", "Декодировать"))
        self.radioNoise.setText(_translate("MainWindow", "Пошуметь"))
        self.buttonBrowse.setText(_translate("MainWindow", "Открыть..."))
        self.buttonEnter.setText(_translate("MainWindow", "Пуск"))
        self.radioNoise.clicked.connect(self.enabled)
        self.radioDecode.clicked.connect(self.disabled)
        self.radioEncode.clicked.connect(self.disabled)
        self.buttonBrowse.clicked.connect(self.showDialog)
        self.slider.valueChanged[int].connect(self.changeValue)

    def changeValue(self, value):
        if value <= 14:
            self.errors.setText('1')
        if value > 14 and value <= 28:
            self.errors.setText('2')
        if value > 28 and value <= 42:
            self.errors.setText('3')
        if value > 42 and value <= 56:
            self.errors.setText('4')
        if value > 56 and value <= 70:
            self.errors.setText('5')
        if value > 70 and value <= 84:
            self.errors.setText('6')
        if value > 84 and value <= 99:
            self.errors.setText('7')
        
    def showDialog(self):
        path = os.path.dirname(__file__)
        if self.radioEncode.isChecked() or self.radioNoise.isChecked():
            fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Open file', path, '*.jpg')[0]
        if self.radioDecode.isChecked():
            fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Open file', path, '*.json')[0]
        self.textEdit.setText(fname)

    def enabled(self):
        self.buttonBrowse.setEnabled(True)
        self.textEdit.setText('')
        self.slider.setEnabled(True)
#         self.slider.setStyleSheet("\n"
# "QSlider::groove:horizontal {  \n"
# "                height: 10px;\n"
# "                margin: 0px;\n"
# "                border-radius: 5px;\n"
# "                background: #B0AEB1;\n"
# "            }\n"
# "QSlider::handle:horizontal {\n"
# "                background: #fff;\n"
# "                border: 1px solid #E3DEE2;\n"
# "                width: 17px;\n"
# "                margin: -5px 0; \n"
# "                border-radius: 8px;\n"
# "            }\n"
# "QSlider::sub-page:qlineargradient {\n"
# "                background: #3B99FC;\n"
# "                border-radius: 5px;\n"
# "            }")
        self.errors.setEnabled(True)

    def disabled(self):
        self.buttonBrowse.setEnabled(True)
        self.textEdit.setText('')
        self.slider.setEnabled(False)
        self.slider.setStyleSheet("\n"
"QSlider::groove:horizontal {  \n"
"                height: 10px;\n"
"                margin: 0px;\n"
"                border-radius: 5px;\n"
"                background: #B0AEB1;\n"
"            }\n"
"QSlider::handle:horizontal {\n"
"                background: #D9D4D8;\n"
"                border: 1px solid #C7C3C6;\n"
"                width: 17px;\n"
"                margin: -5px 0; \n"
"                border-radius: 8px;\n"
"            }\n"
"QSlider::sub-page:qlineargradient {\n"
"                background: #A2CDFC;\n"
"                border-radius: 5px;\n"
"            }")
        self.errors.setEnabled(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
